# Generated by Django 5.1.3 on 2024-12-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
